### ISSUE TITLE
Login credentials not working under Linux

### ISSUE THREAD

**Issue by gabryelreyes** [NewTec-GmbH/pyJiraCli#36]
Current implementation of [cryto_file_handler.py](https://github.com/NewTec-GmbH/pyJiraCli/blob/58d14542896c7b66a96ab9f748b45c4ce4c2a17e/src/pyJiraCli/crypto_file_handler.py) does not work under Linux.

Steps to reproduce:
- Install `pyJiraCli` using `pip install .`
- Run `pyJiraCli login --server hello`  so that it tries to use the encrypted file.

Traceback:
```
Traceback (most recent call last):
  File "/home/greyes/miniconda3/envs/py38/bin/pyJiraCli", line 8, in <module>
    sys.exit(main())
  File "/home/greyes/miniconda3/envs/py38/lib/python3.8/site-packages/pyJiraCli/__main__.py", line 161, in main
    ret_status = args.func(args)
  File "/home/greyes/miniconda3/envs/py38/lib/python3.8/site-packages/pyJiraCli/cmd_login.py", line 157, in execute
    return _cmd_login(args)
  File "/home/greyes/miniconda3/envs/py38/lib/python3.8/site-packages/pyJiraCli/cmd_login.py", line 173, in _cmd_login
    ret_status = _store_login_info(args)
  File "/home/greyes/miniconda3/envs/py38/lib/python3.8/site-packages/pyJiraCli/cmd_login.py", line 206, in _store_login_info
    ret_status = _store_information(data1, data2, args, expiration_date)
  File "/home/greyes/miniconda3/envs/py38/lib/python3.8/site-packages/pyJiraCli/cmd_login.py", line 224, in _store_information
    crypto_h = Crypto()
  File "/home/greyes/miniconda3/envs/py38/lib/python3.8/site-packages/pyJiraCli/crypto_file_handler.py", line 101, in __init__
    self._root_key = _get_device_root_key()
  File "/home/greyes/miniconda3/envs/py38/lib/python3.8/site-packages/pyJiraCli/crypto_file_handler.py", line 543, in _get_device_root_key
    _uuid = sub.check_output(UUID_CMD_UNIX).replace('"', '\n').split()[-1]
TypeError: a bytes-like object is required, not 'str'
```

**Comment by gabryelreyes** [comment]
Possible change of handling passwords using Keyring:
https://github.com/jaraco/keyring

Simple file encryption:
https://github.com/frispete/keyrings.cryptfile
